### ISSUE TITLE
Add 010PHP recurring event to calender stream

### ISSUE THREAD

**Issue by Caroga** [phpnl/devugs#6]
I don't know where or how to do so, but please add 010PHP to the calender stuff.
Our meetups are generally on every second Thursday of the month, starting at 19:00.
thank you very much!

**Comment by jelrikvh** [comment]
You can just submit a pull request for that.

**Comment by Caroga** [comment]
A PR that can add me to the following? https://www.google.com/calendar/embed?src=services%40atimmer.com&ctz=Europe/Amsterdam

Where to do so ?

**Comment by Caroga** [comment]
@atimmer added us to the calendar, thank you!
